# Generated by Django 4.0.6 on 2022-07-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninepyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='explanation',
            field=models.TextField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(),
        ),
    ]
